version: 0.2
    
phases:
  install:
    runtime-versions:
        docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
       - docker build
  post_build:
    commands:
       - docker push
