version: 0.2

env:
      
phases:
  install:
    runtime-versions:
        docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
       - docker-compose build
       - docker-compose push
