version: 0.2
    
phases:
  install:
    runtime-versions:
        docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
       - npm install
       - docker build -t test:1.0 .
       - docker tag test:1.0 288732232203.dkr.ecr.eu-central-1.amazonaws.com/test:latest
  post_build:
    commands:
       - docker push 288732232203.dkr.ecr.eu-central-1.amazonaws.com/test:latest
